### ISSUE TITLE
Warning 4675 is not defined in MSVC

### ISSUE THREAD

**Issue by Guillaumebeuzeboc** [boostorg/move#40]
The warning 4675 is disabled here: https://github.com/boostorg/move/blob/develop/include/boost/move/detail/config_begin.hpp#L17

But this warning doesn't exist in MSVC (tested on Win10 with MSVC v14.28.29910). 
Thus, it generates the warning C4619: `#pragma warning : there is no warning number '4675'`
If the project activate warning as errors it prevents the compilation

**Comment by igaztanaga** [comment]
Looks like the warning was removed in recent compilers. Following:

https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4179?view=msvc-160

we'll disable 4619 warning until all supported compilers don't allow 4675.
