### ISSUE TITLE
Disabling forceinline with Clang broke the build

### ISSUE THREAD

**Issue by alandefreitas** [boostorg/move#50]
https://github.com/alandefreitas/url/actions/runs/4737166802/jobs/8410131446 broke the build.

Lots of errors like:

```
./boost/move/utility_core.hpp:290:7: error: 'BOOST_MOVE_FORCEINLINE' does not name a type
       BOOST_MOVE_FORCEINLINE T&& move_if_not_lvalue_reference(typename ::boost::move_detail::remove_reference<T>::type& t) BOOST_NOEXCEPT
       ^
```

It looks like the commit https://github.com/boostorg/move/commit/a6cdf134d09f705ba8762c7e9d5e2490cfdcce8d simply removed BOOST_MOVE_FORCEINLINE instead of defining it as empty but didn't stop using it in other files.

Here's an example: https://github.com/alandefreitas/url/actions/runs/4737166802/jobs/8410131446

**Comment by igaztanaga** [comment]
It looks that my local regression didn't have clang enabled. Many thanks for the quick report.

**Comment by igaztanaga** [comment]
It seems that regression tests in clang are working again:

https://github.com/boostorg/move/actions/runs/4739821058/jobs/8415005405
